apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-storage-pv
  labels:
    app: grafana
    component: storage
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.40.25
    path: /srv/web-content/grafana
