apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-storage-pv
  labels:
    app: prometheus
    component: storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.40.25
    path: /srv/web-content/prometheus
