apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-reader
  namespace: monitoring
  labels:
    app.kubernetes.io/name: monitoring-reader
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: monitoring-access
automountServiceAccountToken: true
