apiVersion: v1
kind: ConfigMap
metadata:
  name: drupal-database-config
data:
  database-settings.inc: |
    <?php
    /**
     * Kubernetes Database Configuration - Production (Drupal 11 Format)
     * Auto-injected by Kubernetes ConfigMap - Exact format from Drupal installer
     */
    
    $databases['default']['default'] = array (
      'database' => 'drupal_prod',
      'username' => 'drupal',
      'password' => 'Drupal123!',
      'prefix' => '',
      'host' => '192.168.40.25',
      'port' => '3306',
      'isolation_level' => 'READ COMMITTED',
      'driver' => 'mysql',
      'namespace' => 'Drupal\\mysql\\Driver\\Database\\mysql',
      'autoload' => 'core/modules/mysql/src/Driver/Database/mysql/',
    );

    // Hash salt for security (use a strong one in production)
    $settings['hash_salt'] = 'kubernetes-prod-hash-salt-change-in-production-67890';

    // Skip permissions hardening for container environment
    $settings['skip_permissions_hardening'] = TRUE;

    // Production trusted host patterns
    $settings['trusted_host_patterns'] = [
      '^drupal\.local$',
      '^192\.168\.40\.11$',
    ];

    // Config sync directory
    if (empty($settings['config_sync_directory'])) {
      $settings['config_sync_directory'] = 'sites/default/files/sync';
    }

    // Production-specific settings
    $config['system.logging']['error_level'] = 'hide';
