apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-nginx-php
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: php-fpm
        env:
        - name: DRUPAL_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
