apiVersion: v1
kind: ConfigMap
metadata:
  name: drupal-database-config
data:
  database-settings.inc: |
    <?php
    /**
     * Kubernetes Database Configuration - Production
     * Auto-injected by Kubernetes ConfigMap
     */
    $databases['default']['default'] = [
      'database' => 'drupal_prod',
      'username' => 'drupal',
      'password' => 'Drupal123!',
      'prefix' => '',
      'host' => '192.168.40.25',
      'port' => '3306',
      'namespace' => 'Drupal\\mysql\\Driver\\Database\\mysql',
      'driver' => 'mysql',
    ];

    // Kubernetes-specific trusted host patterns
    $settings['trusted_host_patterns'] = [
      '^drupal\.local$',
      '^192\.168\.40\.11$',
    ];

    // Production-specific settings
    $config['system.logging']['error_level'] = 'hide';
    $settings['cache']['default'] = 'cache.backend.database';
    
    // Security settings for production
    $settings['update_free_access'] = FALSE;
    $settings['allow_authorize_operations'] = FALSE;
