- op: add
  path: /spec/template/spec/containers/0/env
  value:
    - name: ENV
      value: "PRODUCTION"
    - name: CLUSTER
      value: "k3s"
- op: add
  path: /spec/template/spec/containers/0/resources
  value:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
