apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Production-specific configurations  
namespace: hello-world-prod

patches:
  # Original hello-world deployment
  - target:
      kind: Deployment
      name: hello-world-nginx
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: ENV
            value: "PRODUCTION"
          - name: CLUSTER
            value: "k3s"
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
  # Drupal deployment environment
  - target:
      kind: Deployment
      name: drupal-nginx-php
    path: drupal-patch.yaml
  # Database configuration for production
  - target:
      kind: ConfigMap
      name: drupal-database-config
    path: drupal-db-patch.yaml
  # Storage patches
  - target:
      kind: PersistentVolumeClaim
      name: web-content-pvc
    path: pvc-patch.yaml

# Production-specific labels
labels:
  - pairs:
      environment: production
      cluster: k3s

# Production replica count
replicas:
  - name: hello-world-nginx
    count: 3
  - name: drupal-nginx-php
    count: 3
