apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-content-pv
spec:
  local:
    path: /srv/web-content
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ubuntu-server  # Replace with your actual server hostname
