apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Service
      name: haproxy-ingress-kubernetes-ingress
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer

labels:
  - pairs:
      environment: production
      managed-by: platform-team
      component: ingress-controller
