apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ip-pool.yaml

labels:
  - pairs:
      environment: production
      managed-by: platform-team
      component: load-balancer
