apiVersion: v1
kind: ConfigMap
metadata:
  name: drupal-database-config
  namespace: hello-world
  labels:
    app: drupal
data:
  database-settings.inc: |
    <?php
    /**
     * Kubernetes Database Configuration - Development (Drupal 11 Format)
     * Auto-injected by Kubernetes ConfigMap - Exact format from Drupal installer
     */
    
    $databases['default']['default'] = array (
      'database' => 'drupal_dev',
      'username' => 'drupal',
      'password' => 'Drupal123!',
      'prefix' => '',
      'host' => '192.168.40.25',
      'port' => '3306',
      'isolation_level' => 'READ COMMITTED',
      'driver' => 'mysql',
      'namespace' => 'Drupal\\mysql\\Driver\\Database\\mysql',
      'autoload' => 'core/modules/mysql/src/Driver/Database/mysql/',
    );

    // Hash salt for security
    $settings['hash_salt'] = 'kubernetes-dev-hash-salt-change-in-production-12345';

    // Skip permissions hardening for container environment
    $settings['skip_permissions_hardening'] = TRUE;

    // Kubernetes-specific trusted host patterns
    $settings['trusted_host_patterns'] = [
      '^drupal\.local$',
      '^localhost$',
      '^127\.0\.0\.1$',
      '^192\.168\.40\.11$',
    ];

    // Config sync directory
    if (empty($settings['config_sync_directory'])) {
      $settings['config_sync_directory'] = 'sites/default/files/sync';
    }

    // Development-specific settings
    $config['system.logging']['error_level'] = 'verbose';
