apiVersion: v1
kind: ConfigMap
metadata:
  name: drupal-database-config
  namespace: hello-world
  labels:
    app: drupal
data:
  database-settings.inc: |
    <?php
    /**
     * Kubernetes Database Configuration - Development (Drupal 11 Compatible)
     * Auto-injected by Kubernetes ConfigMap
     * Based on settings.ddev.php pattern
     */
    
    // Simple Drupal 11 database configuration (following ddev pattern)
    $databases['default']['default']['database'] = 'drupal_dev';
    $databases['default']['default']['username'] = 'drupal';
    $databases['default']['default']['password'] = 'Drupal123!';
    $databases['default']['default']['host'] = '192.168.40.25';
    $databases['default']['default']['port'] = 3306;
    $databases['default']['default']['driver'] = 'mysql';

    // Hash salt for security (required by Drupal 11)
    $settings['hash_salt'] = 'kubernetes-dev-hash-salt-change-in-production-12345';

    // Skip permissions hardening for container environment
    $settings['skip_permissions_hardening'] = TRUE;

    // Kubernetes-specific trusted host patterns
    $settings['trusted_host_patterns'] = [
      '^drupal\.local$',
      '^localhost$',
      '^127\.0\.0\.1$',
      '^192\.168\.40\.11$',
    ];

    // Config sync directory
    if (empty($settings['config_sync_directory'])) {
      $settings['config_sync_directory'] = 'sites/default/files/sync';
    }

    // Development-specific settings
    $config['system.logging']['error_level'] = 'verbose';
    $settings['cache']['bins']['render'] = 'cache.backend.null';
    $settings['cache']['bins']['page'] = 'cache.backend.null';
    $settings['cache']['bins']['dynamic_page_cache'] = 'cache.backend.null';
