apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-nginx-php
  namespace: hello-world
  labels:
    app: drupal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
      # nginx container
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        volumeMounts:
        - name: drupal-content
          mountPath: /app
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      
      # php-fpm container
      - name: php-fpm
        image: php:8.3-fpm
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: drupal-content
          mountPath: /app
        - name: database-config
          mountPath: /var/kubernetes
        env:
        # Environment identification
        - name: DRUPAL_ENV
          value: "development"  # Will be overridden by overlays
        - name: KUBERNETES_SERVICE_HOST
          value: "kubernetes.default.svc.cluster.local"
        # PHP configuration
        - name: PHP_MEMORY_LIMIT
          value: "256M"
        - name: PHP_MAX_EXECUTION_TIME
          value: "300"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        # Add readiness probe to ensure PHP-FPM is ready
        readinessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 10
      
      volumes:
      - name: drupal-content
        persistentVolumeClaim:
          claimName: web-content-pvc
      - name: nginx-config
        configMap:
          name: nginx-drupal-config
      - name: database-config
        configMap:
          name: drupal-database-config
