apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - hello-world-namespace.yaml
  - persistent-volume-claim.yaml  # Only PVC in base
  - deployment.yaml
  - service.yaml
  - ingress.yaml

labels:
  - pairs:
      app: hello-world
