apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-content-pv
  labels:
    app: hello-world
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  # Storage type will be patched by overlays
  hostPath:
    path: /tmp/placeholder
    type: DirectoryOrCreate
