apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-nginx-php
spec:
  template:
    spec:
      containers:
      - name: php-fpm
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: drupal-database
              key: DB_NAME_DEV
        - name: DRUPAL_ENV
          value: "development"
