- op: replace
  path: /spec/replicas
  value: 1
- op: add
  path: /spec/template/spec/containers/0/env
  value:
    - name: ENV
      value: "DEVELOPMENT"
    - name: CLUSTER
      value: "kind-local"
