apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-content-pv
spec:
  hostPath:
    path: /tmp/hostpath-provisioner/hello-world-dev/web-content-pvc  # Kind-specific path
    type: DirectoryOrCreate
